[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.26" # Solana version to use

[features]
seeds = true
skip-lint = false

[programs.devnet]
pump = "5EKkfU7mvHHeD6ABq2Ep2ztMKHUfaSfyqmwRDNswuM2T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/sung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
